### ISSUE TITLE
No an issue but additional sites.

### ISSUE THREAD

**Issue by WoefulWrecker** [PikaMikaTuu/huawei-block-list#5]
# Some are personal logs for years, some are your's  but other from elsewhere.
# update-dre.platform.hicloud.com # Update Firmware.
local=/achievement-dre.things.hicloud.com/
local=/adx-dre-op-hicloud-com-dre.appacc.dbankedge.net/
local=/adx-dre.op.hicloud.com.edgekey.net/
local=/adx-dre.op.hicloud.com/
local=/adxcreative-dra.dbankcdn.com/
local=/api-dra.music.hicloud.com/
local=/api.cloud.hicloud.com/
local=/api.cloud.huawei.com/
local=/cdn.hinative.com/
local=/communityfile-drcn.op.hicloud.com/
local=/configdownload-dra.dbankcdn.com/
local=/configserver-dra.platform.hicloud.com/
local=/configserver-dre.platform.hicloud.com/
local=/consumer-tkbdownload.huawei.com/
local=/coupon-dra.iap.hicloud.com/
local=/cs02-pps-drcn.dbankcdn.com.c.cdnhwc1.com/
local=/cs02-pps-drcn.dbankcdn.com.cdn.dnsv1.com/
local=/dnkeeper.hicloud.com/
local=/dsa-sslv6.hispace.hicloud.com.edgekey.net/
local=/eu.mclean.50union.com/
local=/eu.mvconf.50union.com/
local=/events-dra.op.hicloud.com/
local=/events-dre.op.hicloud.com/
local=/gra.hicloud.com/
local=/grs-dbankcloud-com-dre.appacc-region.dbankedge.net/
local=/grs-dbankcloud-com-dre.appacc.dbankedge.net/
local=/grs-dbankcloud.com-dre.appacc-region.dbankedge.net/
local=/grs-dbankcloud.com-dre.appacc.dbankedge.net/
local=/grs.dbankcloud.asia/
local=/grs.dbankcloud.cn/
local=/grs.dbankcloud.com/
local=/grs.dbankcloud.eu/
local=/hag-dre.ai.hicloud.com/
local=/healthactivity-dre.things.hicloud.com/
local=/healthdeviceagent-dre.things.hicloud.com/
local=/hinative.com/
local=/huaweihigame.com/
local=/hwid-dra.platform.hicloud.com/
local=/hwid-dre.platform.hicloud.com/
local=/hwid.platform.hicloud.com/
local=/id-dre.dbankcdn.com/
local=/id.cloud.huawei.com/
local=/id1.cloud.huawei.com/
local=/id2.cloud.huawei.com/
local=/id3.cloud.huawei.com/
local=/id4.cloud.huawei.com/
local=/id5.cloud.huawei.com/
local=/id6.cloud.huawei.com/
local=/id7.cloud.huawei.com/
local=/logbak.hicloud.com/
local=/logservice1.hicloud.com/
local=/metrics-dra.dt.hicloud.com/
local=/metrics.data.hicloud.com/
local=/metrics1.data.hicloud.com/
local=/metrics2.data.hicloud.com/
local=/metrics3.data.hicloud.com/
local=/metrics4.data.hicloud.com/
local=/metrics5.data.hicloud.com/
local=/pay5.hicloud.com/
local=/pushtrs6.push.hicloud.com/
local=/pushtrs7.push.hicloud.com/
local=/rms-dre-platform-dbankcloud-com-dre.appacc-region.dbankedge.net/
local=/rms-dre-platform-dbankcloud-com-dre.appacc.dbankedge.net/
local=/rms-dre-platform-dbankcloud.com-dre.appacc-region.dbankedge.net/
local=/rms-dre-platform-dbankcloud.com-dre.appacc.dbankedge.net/
local=/rms-dre.platform.dbankcloud.com/
local=/sdkserver-dra.op.hicloud.com/
local=/sdkserver-dre.op.hicloud.com/
local=/security-captcha-dre.platform.hicloud.com/
local=/sns7.hicloud.com/
local=/sp-8f237ea3.honzik.avcdn.net/
local=/sp-8f237ea3.vps-v4.u.acvdn.net/
local=/sportsuggest-dre.things.hicloud.com/
local=/store.hispace.hicloud.com/
local=/theme-dra.emui.hicloud.com/
local=/tsms-dre-platform-dbankcloud-com-dre.appacc-region.dbankedge.net/
local=/tsms-dre-platform-dbankcloud-com-dre.appacc.dbankedge.net/
local=/tsms-dre-platform-dbankcloud.com-dre.appacc-region.dbankedge.net/
local=/tsms-dre-platform-dbankcloud.com-dre.appacc.dbankedge.net/
local=/tsms-dre.platform.dbankcloud.com/
local=/upfile5.hicloud.com/
local=/upfile7.hicloud.com/
local=/videocontent-dra.himovie.hicloud.com/

**Comment by deep-bhatt** [comment]
Added. Thanks! :)
